import tkinter
window=tkinter.Tk()
window.title('Two Frames with Widgets')
top_frame=tkinter.Frame(window).pack()
down_frame=tkinter.Frame(window).pack()
btn1=tkinter.Button(top_frame,text='Button1',fg='red').pack()
btn2=tkinter.Button(top_frame,text='Button2',fg='yellow').pack()
btn3=tkinter.Button(down_frame,text='Button3',fg='purple').pack(side='left')
btn4=tkinter.Button(down_frame,text='Button4',fg='blue').pack(side='right')
window.mainloop()
